DROP TABLE IF EXISTS USER_LOGIN;
CREATE TABLE USER_LOGIN (
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
	IS_LESSOR BOOLEAN NOT NULL,
	PRIMARY KEY (EMAIL)
);
-- Password: webadmin
INSERT INTO USER_LOGIN (EMAIL, PASSWORD_HASH, IS_LESSOR) VALUES ('admin@localhost.com', '874b2ad8869a86bdcb99f3f8820d1940', false);

DROP TABLE IF EXISTS LESSEE;
CREATE TABLE LESSEE (
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PHONE long NOT NULL,
	STREET_ADDRESS VARCHAR(255) NOT NULL,
	POSTAL_CODE VARCHAR(255) NOT NULL,
	PRIMARY KEY (EMAIL)
);

DROP TABLE IF EXISTS LESSOR;
CREATE TABLE LESSOR (
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PHONE long NOT NULL,
	STREET_ADDRESS VARCHAR(255) NOT NULL,
	POSTAL_CODE VARCHAR(255) NOT NULL,
	REGISTRATION_NO VARCHAR(255) NOT NULL,
	PRIMARY KEY (EMAIL, REGISTRATION_NO)
);

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
	PRODUCT_ID VARCHAR(255) NOT NULL,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID VARCHAR(255) NOT NULL,
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	RENT VARCHAR(255) NOT NULL,
	QUANTITY INT NOT NULL,
	IMAGE LONGBLOB,
	REGISTRATION_NO VARCHAR(255) NOT NULL,
	PRIMARY KEY (REGISTRATION_NO, PRODUCT_ID)
);

DROP TABLE IF EXISTS CART;
CREATE TABLE CART (
	ID INT NOT NULL AUTO_INCREMENT,
	USER_EMAIL VARCHAR(255) NOT NULL,
	PRODUCT_ID VARCHAR(255) NOT NULL,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	QUANTITY INT NOT NULL,
	COST LONG NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	USER_EMAIL VARCHAR(255) NOT NULL,
	PRODUCT_ID VARCHAR(255) NOT NULL,
	QUANTITY INT NOT NULL,
	COST LONG NOT NULL,
	PAYMENT_DONE BOOLEAN NOT NULL,
	PRIMARY KEY (ORDER_ID)
);